### ISSUE TITLE
Add quamina pattern match library to tools?

### ISSUE THREAD

**Issue by embano1** [boyney123/awesome-eventbridge#2]
[Quamina](https://pkg.go.dev/github.com/timbray/quamina) is an event-pattern match library in Go written by one of the former engineering and design leads of EventBridge. For example, we use it in the [VEBA](http://vmweventbroker.io) project for the AWS EventBridge integration. Let me know if I shall file a PR if it makes sense to add.

**Comment by boyney123** [comment]
Hi @embano1 , thanks for the issue.

Yeah good question! I guess on it's own the context might be lost, or maybe with some context on how it can be used with EventBridge integrations might help? Any more docs/blogs on that part?

What are your thoughtS?

**Comment by embano1** [comment]
I wasn't sure whether, as a library, it would fall under tools. However, it's a great library in all cases where you build custom applications/ingestion to EventBridge. With `quamina` you can reuse EB patterns and filter them in your code/routing logic before sending to EventBridge, and, as a direct benefit, reducing latency and cost.

Since it's built be the former EB lead, I thought it would be a nice addition to your EB resources here :)

**Comment by boyney123** [comment]
Yeah sounds good to me, did you want to raise a PR with the addition in tools :)?
